### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by pageboy-za** [abiosoft/atom-go-imports#1]
[Enter steps to reproduce below:]
1. elected Atom Menu item Packages and go imports 
2. error message pops up 

**Atom Version**: 0.210.0
**System**: Mac OS X 10.11
**Thrown From**: [go-imports](https://github.com/abiosoft/atom-go-imports) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'lastIndexOf' of undefined

```
At /Users/neallepage/.atom/packages/go-imports/lib/go-imports.coffee:23

TypeError: Cannot read property 'lastIndexOf' of undefined
  at Object.module.exports.process (/Users/neallepage/.atom/packages/go-imports/lib/go-imports.coffee:23:20)
  at atom-text-editor.subscriptions.add.atom.commands.add.go-imports:process (/Users/neallepage/.atom/packages/go-imports/lib/go-imports.coffee:13:88)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -2:03.6.0 golang:getmissingtools (atom-text-editor.editor.is-focused)
     -1:32.9.0 golang:goinfo (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
     -1:09.3.0 golang:golint (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
     -0:00.9.0 go-imports:process (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
foundation5-snippets, v0.2.1
go-imports, v0.1.1
go-plus, v3.3.12
go-runtime, v0.2.0
language-r, v0.2.0
linter-lintr, v0.0.1
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by abiosoft** [comment]
Hi, I have not been able to reproduce this. Did you experiencing this before upgrading to OSX El Capitan?

Thanks.
