### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by zq920320** [abiosoft/atom-go-imports#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [go-imports](https://github.com/abiosoft/atom-go-imports) package, v0.1.1
### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at Object.exports.spawn (child_process.js:977:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at Object.module.exports.process (/Users/ZQ/.atom/packages/go-imports/lib/go-imports.coffee:55:24)
    at atom-text-editor.subscriptions.add.atom.commands.add.go-imports:process (/Users/ZQ/.atom/packages/go-imports/lib/go-imports.coffee:20:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
```
### Commands

```
     -0:13.3.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "go-imports": {
    "path": "/Users/ZQ/developtools/go"
  }
}
```
### Installed Packages

``` coffee
# User
atom-runner, v2.4.1
go-imports, v0.1.1
go-plus, v3.3.12
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by SephVelut** [comment]
Can you confirm that goimports can be found from your $PATH?
